export enum IProcessingStatuses {
  NOT_STARTED = "NOT_STARTED",
  TRANCRIBATION = "TRANCRIBATION",
  TRANCRIBATION_DONE ="TRANCRIBATION_DONE",
  GLOSARY = "GLOSARY",
  GLOSARY_DONE = "GLOSARY_DONE",
  CONSPECT = "CONSPECT",
  CONSPECT_DONE = "CONSPECT_DONE",
}